### ISSUE TITLE
it crash after load a exe in x32dbg

### ISSUE THREAD

**Issue by cxj98** [torusrxxx/x64dbgpatchexporter#1]
does nobody dispute this issue? when load plugin in x32dbg is ok, but when using x32dbg load a exe then plugin is error and crash then exit x32dbg debugger, show error follow:

fist popup a message:

![crash 1](https://cloud.githubusercontent.com/assets/11990617/20158634/75d184ca-a716-11e6-94e5-4bfc7ec91956.jpg)

then crash:

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	x32dbg.exe
  应用程序版本:	0.0.2.5
  应用程序时间戳:	58219018
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.18869
  故障模块时间戳:	556363bc
  异常代码:	e06d7363
  异常偏移:	0000c42d
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by mrfearless** [comment]
What plugins are being used?

**Comment by cxj98** [comment]
the condition is without using other plugins. only use this plugin.

**Comment by torusrxxx** [comment]
x32dbg设置成英文版就没事了，具体问题还不太清楚。

**Comment by cxj98** [comment]
那可能是你的这款插件的路径不支持中文字符吧？

**Comment by cxj98** [comment]
另外测试了，导出需要指定某个文件，就是没有的文件非要叫先生成一个，生成一个后导出又失败。你这个插件有严重的 bug 啊。

**Comment by cxj98** [comment]
另外测试了，导出需要指定某个文件，就是没有的文件非要叫先生成一个，生成一个后导出又失败。你这个插件有严重的 bug 啊。

**Comment by cxj98** [comment]
那可能是你的这款插件的路径不支持中文字符吧？另外测试了，导出需要指定某个文件，就是没有的文件非要叫先生成一个，生成一个后导出又失败。你这个插件有严重的 bug 啊。

![ewe](https://cloud.githubusercontent.com/assets/11990617/20158125/823dc80c-a713-11e6-8d62-d686fadded8f.jpg)

**Comment by cxj98** [comment]
那可能是你的这款插件的路径不支持中文字符吧？另外测试了，导出需要指定某个文件，就是没有的文件非要叫先生成一个，生成一个后导出又失败。你这个插件有严重的 bug 啊。

https://cloud.githubusercontent.com/assets/11990617/20158162/a83a4de6-a713-11e6-8231-4c9db101571e.jpg

**Comment by torusrxxx** [comment]
需要先打开一个文件的意思是叫你选择跟插件一起发布的C.txt，你也可以自己制作一个别的模板，之后就能导出了。

**Comment by torusrxxx** [comment]
已修复。
